---
name: release
on:
  pull_request:
    types: [closed]
    branches:
    - main
  push:
    branches:
    - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Publish Module
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and Publish Module
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.NUGET_APIKEY }}
        run: |
          New-Item -Name ./artifacts/SecretManagement.Hashicorp.Vault.KV -ItemType Directory -Force
          Copy-Item -path ./src/* -Destination /tmp/artifacts/SecretManagement.Hashicorp.Vault.KV/
          Publish-Module -Path /tmp/artifacts/SecretManagement.Hashicorp.Vault.KV -NuGetApiKey $env:NUGET_KEY
      - name: Create Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: SecretManagement.Hashicorp.Vault.KV
          path: /tmp/artifacts/SecretManagement.Hashicorp.Vault.KV
          if-no-files-found: error
      - name: "Get Version"
        if: ${{ success() }}
        shell: pwsh
        run: |
          $Version = Test-ModuleManifest -Path /tmp/artifacts/SecretManagement.Hashicorp.Vault.KV
          echo "tag=$Version.Version.ToString()" >> $GITHUB_ENV
          if ($null -eq $($test.privatedata.psdata.prerelease)) {echo "prerelase=false" >> $GITHUB_ENV} else {echo "prerelase=true" >> $GITHUB_ENV}
      - name: "Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SecretManagement.Hashicorp.Vault.KV"
          tag: ${{ env.tag }}
          prerelease: ${{ env.prerelease }}
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}